version: '3.4'

services:
    app:
        build:
            context: .
            target: app-dev
            cache_from:
                - ${APP_IMAGE_NAME}:${DEV_TAG}
                - ${APP_IMAGE_NAME}:dev-latest
        image: ${APP_IMAGE_NAME}:ci
        volumes:
            - .:/app
