<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190329133340 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE stage_periode_soutenance (id INT AUTO_INCREMENT NOT NULL, stage_periode_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, date_rendu_rapport DATETIME NOT NULL, INDEX IDX_DF1DB51FBFDEDA6B (stage_periode_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salle_examen (id INT AUTO_INCREMENT NOT NULL, salle_id INT DEFAULT NULL, departement_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, nb_colonnes INT NOT NULL, nb_rangs INT NOT NULL, capacite INT NOT NULL, places_interdites VARCHAR(255) NOT NULL, INDEX IDX_65CF5313DC304035 (salle_id), INDEX IDX_65CF5313CCF9E01E (departement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notification (id INT AUTO_INCREMENT NOT NULL, etudiant_id INT DEFAULT NULL, personnel_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, type VARCHAR(100) NOT NULL, url VARCHAR(255) NOT NULL, lu TINYINT(1) NOT NULL, type_user VARCHAR(1) NOT NULL, INDEX IDX_BF5476CADDEAB1A3 (etudiant_id), INDEX IDX_BF5476CA1C109075 (personnel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scolarite_promo_matiere (id INT AUTO_INCREMENT NOT NULL, scolarite_promo_id INT DEFAULT NULL, matiere_id INT DEFAULT NULL, min DOUBLE PRECISION NOT NULL, max DOUBLE PRECISION NOT NULL, moyenne DOUBLE PRECISION NOT NULL, nb_etudiants INT NOT NULL, INDEX IDX_545B5C33CB57B82A (scolarite_promo_id), INDEX IDX_545B5C33F46CD258 (matiere_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stage_periode_offre (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, entreprise VARCHAR(255) NOT NULL, ville VARCHAR(255) NOT NULL, document_name VARCHAR(50) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stage_periode_offre_stage_periode (stage_periode_offre_id INT NOT NULL, stage_periode_id INT NOT NULL, INDEX IDX_3EBC879A818A1210 (stage_periode_offre_id), INDEX IDX_3EBC879ABFDEDA6B (stage_periode_id), PRIMARY KEY(stage_periode_offre_id, stage_periode_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE rattrapage (id INT AUTO_INCREMENT NOT NULL, etudiant_id INT DEFAULT NULL, matiere_id INT DEFAULT NULL, personnel_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', date_eval DATE NOT NULL, heure_eval TIME NOT NULL, duree VARCHAR(20) NOT NULL, date_rattrapage DATE DEFAULT NULL, heure_rattrapage TIME DEFAULT NULL, salle VARCHAR(10) DEFAULT NULL, etat_demande VARCHAR(1) NOT NULL, anneeuniversitaire INT NOT NULL, UNIQUE INDEX UNIQ_BDE5586DD17F50A6 (uuid), INDEX IDX_BDE5586DDDEAB1A3 (etudiant_id), INDEX IDX_BDE5586DF46CD258 (matiere_id), INDEX IDX_BDE5586D1C109075 (personnel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE semestre (id INT AUTO_INCREMENT NOT NULL, precedent_id INT DEFAULT NULL, suivant_id INT DEFAULT NULL, decale_id INT DEFAULT NULL, opt_dest_mail_releve_id INT DEFAULT NULL, opt_dest_mail_modif_note_id INT DEFAULT NULL, opt_dest_mail_absence_resp_id INT DEFAULT NULL, annee_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, couleur VARCHAR(20) DEFAULT NULL, ordre_annee INT NOT NULL, ordre_lmd INT NOT NULL, actif TINYINT(1) NOT NULL, nb_groupes_td INT NOT NULL, nb_groupes_tp INT NOT NULL, opt_mail_releve TINYINT(1) NOT NULL, opt_mail_modification_note TINYINT(1) NOT NULL, opt_evaluation_visible TINYINT(1) NOT NULL, opt_evaluation_modifiable TINYINT(1) NOT NULL, opt_penalite_absence TINYINT(1) NOT NULL, opt_mail_absence_resp TINYINT(1) NOT NULL, opt_mail_absence_etudiant TINYINT(1) NOT NULL, opt_point_penalite_absence DOUBLE PRECISION NOT NULL, mois_debut INT NOT NULL, code_apogee VARCHAR(20) NOT NULL, code_version VARCHAR(10) NOT NULL, code_departement VARCHAR(10) NOT NULL, INDEX IDX_71688FBC4F6564F9 (precedent_id), INDEX IDX_71688FBC9C2BB0CC (suivant_id), INDEX IDX_71688FBCCF416101 (decale_id), INDEX IDX_71688FBCE2F2E760 (opt_dest_mail_releve_id), INDEX IDX_71688FBC9266B8BA (opt_dest_mail_modif_note_id), INDEX IDX_71688FBCF782170E (opt_dest_mail_absence_resp_id), INDEX IDX_71688FBC543EC5F0 (annee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etudiant (id INT AUTO_INCREMENT NOT NULL, adresse_id INT DEFAULT NULL, semestre_id INT DEFAULT NULL, adresse_parentale_id INT DEFAULT NULL, bac_id INT DEFAULT NULL, roles LONGTEXT NOT NULL, created DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', photo_name VARCHAR(50) NOT NULL, num_etudiant VARCHAR(20) NOT NULL, num_ine VARCHAR(20) DEFAULT NULL, annee_bac INT DEFAULT NULL, boursier TINYINT(1) NOT NULL, demandeur_emploi TINYINT(1) NOT NULL, deleted TINYINT(1) NOT NULL, amenagements_particuliers LONGTEXT DEFAULT NULL, promotion INT NOT NULL, intitule_securite_sociale VARCHAR(255) DEFAULT NULL, adresse_securite_sociale VARCHAR(255) DEFAULT NULL, username VARCHAR(75) NOT NULL, password VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, type_user VARCHAR(75) NOT NULL, nom VARCHAR(75) NOT NULL, prenom VARCHAR(75) NOT NULL, mail_univ VARCHAR(255) NOT NULL, site_univ VARCHAR(255) DEFAULT NULL, mail_perso VARCHAR(255) DEFAULT NULL, site_perso VARCHAR(255) DEFAULT NULL, civilite VARCHAR(3) DEFAULT \'M.\' NOT NULL, date_naissance DATE DEFAULT NULL, tel1 VARCHAR(20) DEFAULT NULL, tel2 VARCHAR(20) DEFAULT NULL, remarque LONGTEXT DEFAULT NULL, signature LONGTEXT DEFAULT NULL, visible TINYINT(1) NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_717E22E3D17F50A6 (uuid), UNIQUE INDEX UNIQ_717E22E3989D9B62 (slug), UNIQUE INDEX UNIQ_717E22E39FCEFE16 (mail_univ), UNIQUE INDEX UNIQ_717E22E34DE7DC5C (adresse_id), INDEX IDX_717E22E35577AFDB (semestre_id), UNIQUE INDEX UNIQ_717E22E3CD22752C (adresse_parentale_id), INDEX IDX_717E22E3E03F15C0 (bac_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE etudiant_groupe (etudiant_id INT NOT NULL, groupe_id INT NOT NULL, INDEX IDX_10C7EA42DDEAB1A3 (etudiant_id), INDEX IDX_10C7EA427A45358C (groupe_id), PRIMARY KEY(etudiant_id, groupe_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE configuration (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, cle VARCHAR(50) NOT NULL, valeur VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_hrs (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(100) NOT NULL, type VARCHAR(20) NOT NULL, inclu_service TINYINT(1) NOT NULL, maximum DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE indisponibilite_personnel (id INT AUTO_INCREMENT NOT NULL, creneau_id INT DEFAULT NULL, semaine_id INT DEFAULT NULL, personnel_id INT DEFAULT NULL, priorite INT NOT NULL, INDEX IDX_C98EDDB57D0729A9 (creneau_id), INDEX IDX_C98EDDB5122EEC90 (semaine_id), INDEX IDX_C98EDDB51C109075 (personnel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE diplome (id INT AUTO_INCREMENT NOT NULL, responsable_diplome_id INT DEFAULT NULL, assistant_diplome_id INT DEFAULT NULL, type_diplome_id INT DEFAULT NULL, departement_id INT DEFAULT NULL, annee_universitaire_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, opt_nb_jours_saisie INT NOT NULL, opt_dilpome_decale TINYINT(1) NOT NULL, opt_suppr_absence TINYINT(1) NOT NULL, opt_methode_calcul VARCHAR(10) NOT NULL, opt_anonymat TINYINT(1) NOT NULL, opt_commentaires_releve TINYINT(1) NOT NULL, opt_espace_perso_visible TINYINT(1) NOT NULL, volume_horaire INT NOT NULL, code_celcat_departement INT NOT NULL, sigle VARCHAR(40) NOT NULL, actif TINYINT(1) NOT NULL, code_apogee VARCHAR(20) NOT NULL, code_version VARCHAR(10) NOT NULL, code_departement VARCHAR(10) NOT NULL, INDEX IDX_EB4C4D4ED2D1AAE2 (responsable_diplome_id), INDEX IDX_EB4C4D4E39A24FD8 (assistant_diplome_id), INDEX IDX_EB4C4D4E3BFB8FC7 (type_diplome_id), INDEX IDX_EB4C4D4ECCF9E01E (departement_id), INDEX IDX_EB4C4D4E544BFD58 (annee_universitaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE modification_note (id INT AUTO_INCREMENT NOT NULL, note_id INT DEFAULT NULL, personnel_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, ancienne_note DOUBLE PRECISION NOT NULL, nouvelle_note DOUBLE PRECISION NOT NULL, INDEX IDX_607975E526ED0855 (note_id), INDEX IDX_607975E51C109075 (personnel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, nom VARCHAR(50) NOT NULL, prenom VARCHAR(50) NOT NULL, fonction VARCHAR(255) NOT NULL, telephone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, portable VARCHAR(20) DEFAULT NULL, civilite VARCHAR(3) NOT NULL, fax VARCHAR(20) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ufr (id INT AUTO_INCREMENT NOT NULL, responsable_id INT DEFAULT NULL, site_principal_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, INDEX IDX_20D7AF9853C59D72 (responsable_id), INDEX IDX_20D7AF988CC2ED5D (site_principal_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ufr_site (ufr_id INT NOT NULL, site_id INT NOT NULL, INDEX IDX_DD5A1B6AA469CB09 (ufr_id), INDEX IDX_DD5A1B6AF6BD1646 (site_id), PRIMARY KEY(ufr_id, site_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document (id INT AUTO_INCREMENT NOT NULL, type_document_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', taille DOUBLE PRECISION NOT NULL, type_fichier VARCHAR(100) NOT NULL, description LONGTEXT DEFAULT NULL, libelle VARCHAR(100) NOT NULL, document_name VARCHAR(50) NOT NULL, UNIQUE INDEX UNIQ_D8698A76D17F50A6 (uuid), INDEX IDX_D8698A768826AFA6 (type_document_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE document_semestre (document_id INT NOT NULL, semestre_id INT NOT NULL, INDEX IDX_FEA97EE5C33F7837 (document_id), INDEX IDX_FEA97EE55577AFDB (semestre_id), PRIMARY KEY(document_id, semestre_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE twig_template (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, name VARCHAR(255) NOT NULL, source LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_groupe (id INT AUTO_INCREMENT NOT NULL, semestre_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(100) NOT NULL, defaut TINYINT(1) NOT NULL, INDEX IDX_276EE7195577AFDB (semestre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE competence (id INT AUTO_INCREMENT NOT NULL, diplome_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, code VARCHAR(20) NOT NULL, INDEX IDX_94D4687F26F859E2 (diplome_id), INDEX IDX_94D4687F727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stage_etudiant (id INT AUTO_INCREMENT NOT NULL, stage_periode_id INT DEFAULT NULL, etudiant_id INT DEFAULT NULL, tuteur_id INT DEFAULT NULL, tuteur_universitaire_id INT DEFAULT NULL, entreprise_id INT DEFAULT NULL, adresse_stage_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, service_stage_entreprise VARCHAR(255) DEFAULT NULL, sujet_stage LONGTEXT DEFAULT NULL, date_depot_formulaire DATETIME DEFAULT NULL, date_validation DATETIME DEFAULT NULL, date_convention_envoyee DATETIME DEFAULT NULL, date_convention_recu DATETIME DEFAULT NULL, etat_stage VARCHAR(30) NOT NULL, date_debut_stage DATE NOT NULL, date_fin_stage DATE NOT NULL, activites LONGTEXT DEFAULT NULL, amenagement_stage LONGTEXT DEFAULT NULL, gratification TINYINT(1) NOT NULL, gratification_montant DOUBLE PRECISION NOT NULL, gratification_periode VARCHAR(1) NOT NULL, avantages LONGTEXT DEFAULT NULL, duree_hebdomadaire DOUBLE PRECISION NOT NULL, duree_jours_stage INT NOT NULL, date_autorise DATETIME DEFAULT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', date_imprime DATETIME DEFAULT NULL, periodes_interruptions LONGTEXT DEFAULT NULL, commentaire_duree_hebdomadaire LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_7999E68ED17F50A6 (uuid), INDEX IDX_7999E68EBFDEDA6B (stage_periode_id), INDEX IDX_7999E68EDDEAB1A3 (etudiant_id), UNIQUE INDEX UNIQ_7999E68E86EC68D8 (tuteur_id), INDEX IDX_7999E68E19FA6F23 (tuteur_universitaire_id), INDEX IDX_7999E68EA4AEAFEA (entreprise_id), UNIQUE INDEX UNIQ_7999E68E428641F9 (adresse_stage_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE absence_justificatif (id INT AUTO_INCREMENT NOT NULL, etudiant_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', date_debut DATE NOT NULL, date_fin DATE NOT NULL, heure_debut TIME NOT NULL, heure_fin TIME NOT NULL, motif VARCHAR(255) NOT NULL, etat VARCHAR(1) NOT NULL, annee_universitaire INT NOT NULL, fichier_name VARCHAR(50) NOT NULL, UNIQUE INDEX UNIQ_79296AB6D17F50A6 (uuid), INDEX IDX_79296AB6DDEAB1A3 (etudiant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scolarite_moyenne_ue (id INT AUTO_INCREMENT NOT NULL, scolarite_id INT DEFAULT NULL, ue_id INT DEFAULT NULL, moyenne DOUBLE PRECISION NOT NULL, rang INT NOT NULL, INDEX IDX_B78918B5AA6B2AB6 (scolarite_id), INDEX IDX_B78918B562E883B1 (ue_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE fichier (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) NOT NULL, taille DOUBLE PRECISION NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE absence (id INT AUTO_INCREMENT NOT NULL, personnel_id INT DEFAULT NULL, matiere_id INT DEFAULT NULL, etudiant_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', date DATE NOT NULL, heure TIME NOT NULL, duree TIME NOT NULL, justifie TINYINT(1) NOT NULL, anneeuniversitaire INT NOT NULL, UNIQUE INDEX UNIQ_765AE0C9D17F50A6 (uuid), INDEX IDX_765AE0C91C109075 (personnel_id), INDEX IDX_765AE0C9F46CD258 (matiere_id), INDEX IDX_765AE0C9DDEAB1A3 (etudiant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE site (id INT AUTO_INCREMENT NOT NULL, adresse_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_694309E44DE7DC5C (adresse_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE help (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, titre VARCHAR(255) NOT NULL, texte LONGTEXT NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ue (id INT AUTO_INCREMENT NOT NULL, semestre_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, numero_ue INT NOT NULL, coefficient DOUBLE PRECISION NOT NULL, nb_ects DOUBLE PRECISION NOT NULL, code_apogee VARCHAR(20) NOT NULL, code_version VARCHAR(10) NOT NULL, code_departement VARCHAR(10) NOT NULL, INDEX IDX_2E490A9B5577AFDB (semestre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stage_mail_template (id INT AUTO_INCREMENT NOT NULL, stage_periode_id INT DEFAULT NULL, twig_template_id INT DEFAULT NULL, subject VARCHAR(255) NOT NULL, event VARCHAR(50) NOT NULL, INDEX IDX_B64E584BBFDEDA6B (stage_periode_id), UNIQUE INDEX UNIQ_B64E584BB08B63B (twig_template_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_destinataire (id INT AUTO_INCREMENT NOT NULL, message_id INT DEFAULT NULL, personnel_id INT DEFAULT NULL, etudiant_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, date_lu DATETIME NOT NULL, etat VARCHAR(1) NOT NULL, typeDestinataire VARCHAR(255) NOT NULL, INDEX IDX_3AA8CA74537A1329 (message_id), INDEX IDX_3AA8CA741C109075 (personnel_id), INDEX IDX_3AA8CA74DDEAB1A3 (etudiant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE alternance (id INT AUTO_INCREMENT NOT NULL, entreprise_id INT DEFAULT NULL, tuteur_id INT DEFAULT NULL, etudiant_id INT DEFAULT NULL, tuteur_universitaire_id INT DEFAULT NULL, annee_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, annee_universitaire INT NOT NULL, type_contrat VARCHAR(20) NOT NULL, etat VARCHAR(10) NOT NULL, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, UNIQUE INDEX UNIQ_445F37B9A4AEAFEA (entreprise_id), UNIQUE INDEX UNIQ_445F37B986EC68D8 (tuteur_id), INDEX IDX_445F37B9DDEAB1A3 (etudiant_id), INDEX IDX_445F37B919FA6F23 (tuteur_universitaire_id), INDEX IDX_445F37B9543EC5F0 (annee_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE edt_planning (id INT AUTO_INCREMENT NOT NULL, jour INT NOT NULL, salle VARCHAR(30) NOT NULL, ordre VARCHAR(20) NOT NULL, debut INT NOT NULL, fin INT NOT NULL, semaine INT NOT NULL, evaluation TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE groupe (id INT AUTO_INCREMENT NOT NULL, type_groupe_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(50) NOT NULL, code_apogee VARCHAR(50) NOT NULL, INDEX IDX_4B98C21CE83749C (type_groupe_id), INDEX IDX_4B98C21727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE actualite (id INT AUTO_INCREMENT NOT NULL, departement_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, titre VARCHAR(150) NOT NULL, texte LONGTEXT NOT NULL, INDEX IDX_54928197CCF9E01E (departement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stage_periode_interruption (id INT AUTO_INCREMENT NOT NULL, stage_periode_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, motif VARCHAR(255) NOT NULL, INDEX IDX_597C69BDBFDEDA6B (stage_periode_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE materiel (id INT AUTO_INCREMENT NOT NULL, type_materiel_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, photo_name VARCHAR(50) NOT NULL, INDEX IDX_18D2B0915D91DD3E (type_materiel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scolarite_moyenne_matiere (id INT AUTO_INCREMENT NOT NULL, scolarite_id INT DEFAULT NULL, matiere_id INT DEFAULT NULL, moyenne DOUBLE PRECISION NOT NULL, rang INT NOT NULL, INDEX IDX_25D9FE28AA6B2AB6 (scolarite_id), INDEX IDX_25D9FE28F46CD258 (matiere_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_materiel (id INT AUTO_INCREMENT NOT NULL, departement_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(100) NOT NULL, INDEX IDX_D52D976DCCF9E01E (departement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE annee_universitaire (id INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(30) NOT NULL, annee INT NOT NULL, commentaire LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE ppn (id INT AUTO_INCREMENT NOT NULL, diplome_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, annee INT NOT NULL, INDEX IDX_2E8584EB26F859E2 (diplome_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE trello_tache (id INT AUTO_INCREMENT NOT NULL, departement_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, deadline DATETIME NOT NULL, description LONGTEXT NOT NULL, INDEX IDX_2589CEE0CCF9E01E (departement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE trello_tache_personnel (trello_tache_id INT NOT NULL, personnel_id INT NOT NULL, INDEX IDX_7D360FA2EBED4F1 (trello_tache_id), INDEX IDX_7D360FA21C109075 (personnel_id), PRIMARY KEY(trello_tache_id, personnel_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message_piece_jointe (id INT AUTO_INCREMENT NOT NULL, message_id INT DEFAULT NULL, fichier VARCHAR(50) NOT NULL, extension VARCHAR(5) NOT NULL, INDEX IDX_6F502432537A1329 (message_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE entreprise (id INT AUTO_INCREMENT NOT NULL, adresse_id INT DEFAULT NULL, responsable_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, siret VARCHAR(30) NOT NULL, raison_sociale VARCHAR(255) NOT NULL, libelle VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_D19FA604DE7DC5C (adresse_id), UNIQUE INDEX UNIQ_D19FA6053C59D72 (responsable_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE borne (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, icone VARCHAR(20) NOT NULL, couleur VARCHAR(20) NOT NULL, message LONGTEXT NOT NULL, url VARCHAR(255) DEFAULT NULL, date_debut_publication DATETIME NOT NULL, date_fin_publication DATETIME NOT NULL, visible TINYINT(1) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE borne_semestre (borne_id INT NOT NULL, semestre_id INT NOT NULL, INDEX IDX_D1378E3B7F023A56 (borne_id), INDEX IDX_D1378E3B5577AFDB (semestre_id), PRIMARY KEY(borne_id, semestre_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message (id INT AUTO_INCREMENT NOT NULL, expediteur_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, sujet VARCHAR(100) NOT NULL, message LONGTEXT NOT NULL, important TINYINT(1) NOT NULL, INDEX IDX_B6BD307F10335F61 (expediteur_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_diplome (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, sigle VARCHAR(20) NOT NULL, nb_semestres INT NOT NULL, niveau_entree INT NOT NULL, niveau_sortie INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE note (id INT AUTO_INCREMENT NOT NULL, evaluation_id INT DEFAULT NULL, etudiant_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', note DOUBLE PRECISION NOT NULL, commentaire VARCHAR(255) NOT NULL, absence_justifie TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_CFBDFA14D17F50A6 (uuid), INDEX IDX_CFBDFA14456C5646 (evaluation_id), INDEX IDX_CFBDFA14DDEAB1A3 (etudiant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE favori (id INT AUTO_INCREMENT NOT NULL, etudiant_demandeur_id INT DEFAULT NULL, etudiant_demande_id INT DEFAULT NULL, date_ajout DATETIME NOT NULL, INDEX IDX_EF85A2CC9D7BCD43 (etudiant_demandeur_id), INDEX IDX_EF85A2CC4E463162 (etudiant_demande_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE previsionnel (id INT AUTO_INCREMENT NOT NULL, matiere_id INT DEFAULT NULL, personnel_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, annee INT NOT NULL, referent TINYINT(1) NOT NULL, nb_hcm DOUBLE PRECISION NOT NULL, nb_htd DOUBLE PRECISION NOT NULL, nb_htp DOUBLE PRECISION NOT NULL, nb_gr_cm INT NOT NULL, nb_gr_td INT NOT NULL, nb_gr_tp INT NOT NULL, INDEX IDX_AE25C261F46CD258 (matiere_id), INDEX IDX_AE25C2611C109075 (personnel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evaluation (id INT AUTO_INCREMENT NOT NULL, matiere_id INT DEFAULT NULL, personnel_auteur_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, type_groupe_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', date_evaluation DATE NOT NULL, anneeuniversitaire INT NOT NULL, visible TINYINT(1) NOT NULL, modifiable TINYINT(1) NOT NULL, coefficient DOUBLE PRECISION NOT NULL, commentaire VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_1323A575D17F50A6 (uuid), INDEX IDX_1323A575F46CD258 (matiere_id), INDEX IDX_1323A57566A6ABE2 (personnel_auteur_id), INDEX IDX_1323A575727ACA70 (parent_id), INDEX IDX_1323A575CE83749C (type_groupe_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE evaluation_personnel (evaluation_id INT NOT NULL, personnel_id INT NOT NULL, INDEX IDX_74BC385A456C5646 (evaluation_id), INDEX IDX_74BC385A1C109075 (personnel_id), PRIMARY KEY(evaluation_id, personnel_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE personnel_departement (id INT AUTO_INCREMENT NOT NULL, personnel_id INT DEFAULT NULL, departement_id INT DEFAULT NULL, annee INT NOT NULL, roles VARCHAR(250) NOT NULL, defaut TINYINT(1) NOT NULL, INDEX IDX_39139ED31C109075 (personnel_id), INDEX IDX_39139ED3CCF9E01E (departement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE courrier (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, texte LONGTEXT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, departement_id INT DEFAULT NULL, personnel_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, titre VARCHAR(255) NOT NULL, texte LONGTEXT NOT NULL, slug VARCHAR(255) NOT NULL, type VARCHAR(20) NOT NULL, INDEX IDX_23A0E66CCF9E01E (departement_id), INDEX IDX_23A0E661C109075 (personnel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_semestre (article_id INT NOT NULL, semestre_id INT NOT NULL, INDEX IDX_24807BD77294869C (article_id), INDEX IDX_24807BD75577AFDB (semestre_id), PRIMARY KEY(article_id, semestre_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE article_etudiant (article_id INT NOT NULL, etudiant_id INT NOT NULL, INDEX IDX_2496D6887294869C (article_id), INDEX IDX_2496D688DDEAB1A3 (etudiant_id), PRIMARY KEY(article_id, etudiant_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scolarite (id INT AUTO_INCREMENT NOT NULL, semestre_id INT DEFAULT NULL, etudiant_id INT DEFAULT NULL, annee_universitaire_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', ordre INT NOT NULL, decision VARCHAR(10) NOT NULL, proposition VARCHAR(10) DEFAULT NULL, moyenne DOUBLE PRECISION NOT NULL, nb_absences INT NOT NULL, commentaire LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_276250ABD17F50A6 (uuid), INDEX IDX_276250AB5577AFDB (semestre_id), INDEX IDX_276250ABDDEAB1A3 (etudiant_id), INDEX IDX_276250AB544BFD58 (annee_universitaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE salle (id INT AUTO_INCREMENT NOT NULL, site_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(30) NOT NULL, capacite INT NOT NULL, type VARCHAR(255) NOT NULL, INDEX IDX_4E977E5CF6BD1646 (site_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cahier_texte (id INT AUTO_INCREMENT NOT NULL, personnel_id INT DEFAULT NULL, semestre_id INT DEFAULT NULL, matiere_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(150) NOT NULL, description LONGTEXT NOT NULL, date_retour DATETIME NOT NULL, INDEX IDX_B554C6181C109075 (personnel_id), INDEX IDX_B554C6185577AFDB (semestre_id), INDEX IDX_B554C618F46CD258 (matiere_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cahier_texte_fichier (cahier_texte_id INT NOT NULL, fichier_id INT NOT NULL, INDEX IDX_A095F9C885D2D268 (cahier_texte_id), INDEX IDX_A095F9C8F915CFE (fichier_id), PRIMARY KEY(cahier_texte_id, fichier_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hrs (id INT AUTO_INCREMENT NOT NULL, semestre_id INT DEFAULT NULL, diplome_id INT DEFAULT NULL, personnel_id INT DEFAULT NULL, type_hrs_id INT DEFAULT NULL, departement_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, nb_heures_td DOUBLE PRECISION NOT NULL, libelle VARCHAR(150) NOT NULL, annee INT NOT NULL, INDEX IDX_6D8078785577AFDB (semestre_id), INDEX IDX_6D80787826F859E2 (diplome_id), INDEX IDX_6D8078781C109075 (personnel_id), INDEX IDX_6D807878152AE753 (type_hrs_id), INDEX IDX_6D807878CCF9E01E (departement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE creneau_bloque (id INT AUTO_INCREMENT NOT NULL, creneau_id INT DEFAULT NULL, semaine_id INT DEFAULT NULL, texte VARCHAR(255) DEFAULT NULL, obligatoire TINYINT(1) NOT NULL, type VARCHAR(2) NOT NULL, INDEX IDX_441F29EE7D0729A9 (creneau_id), INDEX IDX_441F29EE122EEC90 (semaine_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE parcour (id INT AUTO_INCREMENT NOT NULL, semestre_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, code_apogee VARCHAR(20) NOT NULL, code_version VARCHAR(10) NOT NULL, code_departement VARCHAR(10) NOT NULL, INDEX IDX_B7E529565577AFDB (semestre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scolarite_promo (id INT AUTO_INCREMENT NOT NULL, semestre_id INT DEFAULT NULL, annee_universitaire_id INT DEFAULT NULL, min DOUBLE PRECISION NOT NULL, max DOUBLE PRECISION NOT NULL, nb_etudiants INT NOT NULL, moyenne DOUBLE PRECISION NOT NULL, INDEX IDX_DDCE376C5577AFDB (semestre_id), INDEX IDX_DDCE376C544BFD58 (annee_universitaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE date (id INT AUTO_INCREMENT NOT NULL, departement_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, texte LONGTEXT DEFAULT NULL, date_debut DATE NOT NULL, heure_debut TIME DEFAULT NULL, date_fin DATE NOT NULL, heure_fin TIME DEFAULT NULL, lieu VARCHAR(150) NOT NULL, allday TINYINT(1) NOT NULL, qui VARCHAR(1) NOT NULL, type VARCHAR(30) NOT NULL, INDEX IDX_AA9E377ACCF9E01E (departement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE date_semestre (date_id INT NOT NULL, semestre_id INT NOT NULL, INDEX IDX_B25DE61AB897366B (date_id), INDEX IDX_B25DE61A5577AFDB (semestre_id), PRIMARY KEY(date_id, semestre_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bac (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(30) NOT NULL, libelle_long VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE celcat_events (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, event_id INT NOT NULL, jour INT NOT NULL, debut DATETIME NOT NULL, fin DATETIME NOT NULL, semaine_formation INT NOT NULL, type VARCHAR(20) NOT NULL, code_module VARCHAR(20) NOT NULL, lib_module VARCHAR(255) NOT NULL, code_personnel VARCHAR(20) NOT NULL, lib_personnel VARCHAR(255) NOT NULL, departement_id INT NOT NULL, code_salle VARCHAR(20) NOT NULL, lib_salle VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE departement (id INT AUTO_INCREMENT NOT NULL, ufr_id INT DEFAULT NULL, respri_id INT DEFAULT NULL, annee_universitaire_prepare_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', libelle VARCHAR(255) NOT NULL, logo_name VARCHAR(50) NOT NULL, tel_contact VARCHAR(16) DEFAULT NULL, fax VARCHAR(16) DEFAULT NULL, couleur VARCHAR(16) DEFAULT NULL, site_web VARCHAR(255) DEFAULT NULL, description LONGTEXT DEFAULT NULL, opt_update_celcat TINYINT(1) NOT NULL, opt_agence TINYINT(1) NOT NULL, opt_materiel TINYINT(1) NOT NULL, opt_edt TINYINT(1) NOT NULL, opt_stage TINYINT(1) NOT NULL, opt_synthese TINYINT(1) NOT NULL, opt_messagerie TINYINT(1) NOT NULL, opt_infos TINYINT(1) NOT NULL, opt_annee_previsionnel INT NOT NULL, actif TINYINT(1) NOT NULL, preparation_annee TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_C1765B63D17F50A6 (uuid), INDEX IDX_C1765B63A469CB09 (ufr_id), INDEX IDX_C1765B632AC98151 (respri_id), INDEX IDX_C1765B63EB0464C9 (annee_universitaire_prepare_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stage_periode (id INT AUTO_INCREMENT NOT NULL, semestre_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, uuid BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid_binary)\', document_name VARCHAR(50) NOT NULL, numero_periode INT NOT NULL, libelle VARCHAR(100) NOT NULL, nb_semaines INT NOT NULL, nb_jours INT NOT NULL, date_debut DATE NOT NULL, date_fin DATE NOT NULL, competences_visees LONGTEXT NOT NULL, modalite_evaluation LONGTEXT NOT NULL, modalite_evaluation_pedagogique LONGTEXT NOT NULL, modalite_encadrement LONGTEXT NOT NULL, document_rendre VARCHAR(255) NOT NULL, nb_ects DOUBLE PRECISION NOT NULL, dates_flexibles TINYINT(1) NOT NULL, copie_assistant TINYINT(1) NOT NULL, annee_universitaire INT NOT NULL, texte_libre LONGTEXT NOT NULL, UNIQUE INDEX UNIQ_193A6DBED17F50A6 (uuid), INDEX IDX_193A6DBE5577AFDB (semestre_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE stage_periode_personnel (stage_periode_id INT NOT NULL, personnel_id INT NOT NULL, INDEX IDX_30781912BFDEDA6B (stage_periode_id), INDEX IDX_307819121C109075 (personnel_id), PRIMARY KEY(stage_periode_id, personnel_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE creneau_cours (id INT AUTO_INCREMENT NOT NULL, annee_universitaire_id INT DEFAULT NULL, departement_id INT DEFAULT NULL, jour INT NOT NULL, debut TIME NOT NULL, fin TIME NOT NULL, INDEX IDX_E844BB21544BFD58 (annee_universitaire_id), INDEX IDX_E844BB21CCF9E01E (departement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE adresse (id INT AUTO_INCREMENT NOT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, adresse1 VARCHAR(255) DEFAULT NULL, adresse2 VARCHAR(255) DEFAULT NULL, adresse3 VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(10) DEFAULT NULL, ville VARCHAR(100) DEFAULT NULL, pays VARCHAR(100) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE calendrier (id INT AUTO_INCREMENT NOT NULL, annee_universitaire_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, semaine_formation INT NOT NULL, semaine_reelle INT NOT NULL, date_lundi DATETIME NOT NULL, INDEX IDX_B2753CB9544BFD58 (annee_universitaire_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE personnel (id INT AUTO_INCREMENT NOT NULL, adresse_id INT DEFAULT NULL, roles LONGTEXT NOT NULL, created DATETIME NOT NULL, statut VARCHAR(10) NOT NULL, poste_interne VARCHAR(10) DEFAULT NULL, tel_bureau VARCHAR(20) DEFAULT NULL, responsabilites LONGTEXT DEFAULT NULL, domaines LONGTEXT DEFAULT NULL, entreprise VARCHAR(255) DEFAULT NULL, bureau1 VARCHAR(20) DEFAULT NULL, bureau2 VARCHAR(20) DEFAULT NULL, numero_harpege INT DEFAULT NULL, initiales VARCHAR(10) DEFAULT NULL, cv_name VARCHAR(50) DEFAULT NULL, photo_name VARCHAR(50) NOT NULL, nb_heures_service DOUBLE PRECISION NOT NULL, deleted TINYINT(1) NOT NULL, couleur VARCHAR(20) DEFAULT NULL, username VARCHAR(75) NOT NULL, password VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, type_user VARCHAR(75) NOT NULL, nom VARCHAR(75) NOT NULL, prenom VARCHAR(75) NOT NULL, mail_univ VARCHAR(255) NOT NULL, site_univ VARCHAR(255) DEFAULT NULL, mail_perso VARCHAR(255) DEFAULT NULL, site_perso VARCHAR(255) DEFAULT NULL, civilite VARCHAR(3) DEFAULT \'M.\' NOT NULL, date_naissance DATE DEFAULT NULL, tel1 VARCHAR(20) DEFAULT NULL, tel2 VARCHAR(20) DEFAULT NULL, remarque LONGTEXT DEFAULT NULL, signature LONGTEXT DEFAULT NULL, visible TINYINT(1) NOT NULL, updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_A6BCF3DE989D9B62 (slug), UNIQUE INDEX UNIQ_A6BCF3DE9FCEFE16 (mail_univ), UNIQUE INDEX UNIQ_A6BCF3DE4DE7DC5C (adresse_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE matiere (id INT AUTO_INCREMENT NOT NULL, ue_id INT DEFAULT NULL, ppn_id INT DEFAULT NULL, parcours_id INT DEFAULT NULL, matiere_parent_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, code_matiere VARCHAR(20) NOT NULL, cm_ppn DOUBLE PRECISION NOT NULL, td_ppn DOUBLE PRECISION NOT NULL, tp_ppn DOUBLE PRECISION NOT NULL, cm_formation DOUBLE PRECISION NOT NULL, td_formation DOUBLE PRECISION NOT NULL, tp_formation DOUBLE PRECISION NOT NULL, commentaire LONGTEXT DEFAULT NULL, nb_notes INT NOT NULL, coefficient DOUBLE PRECISION NOT NULL, pac TINYINT(1) NOT NULL, nb_ects DOUBLE PRECISION NOT NULL, objectifs_module LONGTEXT DEFAULT NULL, competences_visees LONGTEXT DEFAULT NULL, contenu LONGTEXT DEFAULT NULL, pre_requis LONGTEXT DEFAULT NULL, modalites LONGTEXT DEFAULT NULL, prolongements LONGTEXT DEFAULT NULL, mots_cles LONGTEXT DEFAULT NULL, suspendu TINYINT(1) NOT NULL, code_apogee VARCHAR(20) NOT NULL, code_version VARCHAR(10) NOT NULL, code_departement VARCHAR(10) NOT NULL, INDEX IDX_9014574A62E883B1 (ue_id), INDEX IDX_9014574A1CBD0BF (ppn_id), INDEX IDX_9014574A6E38C0DB (parcours_id), INDEX IDX_9014574AB7749956 (matiere_parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE scolarite_promo_ue (id INT AUTO_INCREMENT NOT NULL, scolarite_promo_id INT DEFAULT NULL, ue_id INT DEFAULT NULL, min DOUBLE PRECISION NOT NULL, max DOUBLE PRECISION NOT NULL, moyenne DOUBLE PRECISION NOT NULL, nb_etudiants INT NOT NULL, INDEX IDX_5A27D5E1CB57B82A (scolarite_promo_id), INDEX IDX_5A27D5E162E883B1 (ue_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE annee (id INT AUTO_INCREMENT NOT NULL, diplome_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(255) NOT NULL, ordre INT NOT NULL, couleurCM VARCHAR(7) DEFAULT NULL, couleurTD VARCHAR(7) DEFAULT NULL, couleurTP VARCHAR(7) DEFAULT NULL, couleurtexte VARCHAR(7) DEFAULT NULL, libelle_long VARCHAR(150) DEFAULT NULL, opt_alternance TINYINT(1) NOT NULL, actif TINYINT(1) NOT NULL, code_apogee VARCHAR(20) NOT NULL, code_version VARCHAR(10) NOT NULL, code_departement VARCHAR(10) NOT NULL, INDEX IDX_DE92C5CF26F859E2 (diplome_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE materiel_pret (id INT AUTO_INCREMENT NOT NULL, departement_id INT DEFAULT NULL, etudiant_id INT DEFAULT NULL, personnel_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, date_demande DATETIME NOT NULL, date_debut_emprunt DATETIME NOT NULL, date_fin_emprunt DATETIME NOT NULL, date_validation DATETIME NOT NULL, etat_demande VARCHAR(1) NOT NULL, motif VARCHAR(255) NOT NULL, telephone VARCHAR(15) NOT NULL, justification VARCHAR(255) NOT NULL, INDEX IDX_F2CBA05FCCF9E01E (departement_id), INDEX IDX_F2CBA05FDDEAB1A3 (etudiant_id), INDEX IDX_F2CBA05F1C109075 (personnel_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE type_document (id INT AUTO_INCREMENT NOT NULL, departement_id INT DEFAULT NULL, created DATETIME NOT NULL, updated DATETIME NOT NULL, libelle VARCHAR(75) NOT NULL, INDEX IDX_1596AD8ACCF9E01E (departement_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE stage_periode_soutenance ADD CONSTRAINT FK_DF1DB51FBFDEDA6B FOREIGN KEY (stage_periode_id) REFERENCES stage_periode (id)');
        $this->addSql('ALTER TABLE salle_examen ADD CONSTRAINT FK_65CF5313DC304035 FOREIGN KEY (salle_id) REFERENCES salle (id)');
        $this->addSql('ALTER TABLE salle_examen ADD CONSTRAINT FK_65CF5313CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CADDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA1C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE scolarite_promo_matiere ADD CONSTRAINT FK_545B5C33CB57B82A FOREIGN KEY (scolarite_promo_id) REFERENCES scolarite_promo (id)');
        $this->addSql('ALTER TABLE scolarite_promo_matiere ADD CONSTRAINT FK_545B5C33F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE stage_periode_offre_stage_periode ADD CONSTRAINT FK_3EBC879A818A1210 FOREIGN KEY (stage_periode_offre_id) REFERENCES stage_periode_offre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stage_periode_offre_stage_periode ADD CONSTRAINT FK_3EBC879ABFDEDA6B FOREIGN KEY (stage_periode_id) REFERENCES stage_periode (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rattrapage ADD CONSTRAINT FK_BDE5586DDDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE rattrapage ADD CONSTRAINT FK_BDE5586DF46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE rattrapage ADD CONSTRAINT FK_BDE5586D1C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE semestre ADD CONSTRAINT FK_71688FBC4F6564F9 FOREIGN KEY (precedent_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE semestre ADD CONSTRAINT FK_71688FBC9C2BB0CC FOREIGN KEY (suivant_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE semestre ADD CONSTRAINT FK_71688FBCCF416101 FOREIGN KEY (decale_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE semestre ADD CONSTRAINT FK_71688FBCE2F2E760 FOREIGN KEY (opt_dest_mail_releve_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE semestre ADD CONSTRAINT FK_71688FBC9266B8BA FOREIGN KEY (opt_dest_mail_modif_note_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE semestre ADD CONSTRAINT FK_71688FBCF782170E FOREIGN KEY (opt_dest_mail_absence_resp_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE semestre ADD CONSTRAINT FK_71688FBC543EC5F0 FOREIGN KEY (annee_id) REFERENCES annee (id)');
        $this->addSql('ALTER TABLE etudiant ADD CONSTRAINT FK_717E22E34DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE etudiant ADD CONSTRAINT FK_717E22E35577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE etudiant ADD CONSTRAINT FK_717E22E3CD22752C FOREIGN KEY (adresse_parentale_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE etudiant ADD CONSTRAINT FK_717E22E3E03F15C0 FOREIGN KEY (bac_id) REFERENCES bac (id)');
        $this->addSql('ALTER TABLE etudiant_groupe ADD CONSTRAINT FK_10C7EA42DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE etudiant_groupe ADD CONSTRAINT FK_10C7EA427A45358C FOREIGN KEY (groupe_id) REFERENCES groupe (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE indisponibilite_personnel ADD CONSTRAINT FK_C98EDDB57D0729A9 FOREIGN KEY (creneau_id) REFERENCES creneau_cours (id)');
        $this->addSql('ALTER TABLE indisponibilite_personnel ADD CONSTRAINT FK_C98EDDB5122EEC90 FOREIGN KEY (semaine_id) REFERENCES calendrier (id)');
        $this->addSql('ALTER TABLE indisponibilite_personnel ADD CONSTRAINT FK_C98EDDB51C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE diplome ADD CONSTRAINT FK_EB4C4D4ED2D1AAE2 FOREIGN KEY (responsable_diplome_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE diplome ADD CONSTRAINT FK_EB4C4D4E39A24FD8 FOREIGN KEY (assistant_diplome_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE diplome ADD CONSTRAINT FK_EB4C4D4E3BFB8FC7 FOREIGN KEY (type_diplome_id) REFERENCES type_diplome (id)');
        $this->addSql('ALTER TABLE diplome ADD CONSTRAINT FK_EB4C4D4ECCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE diplome ADD CONSTRAINT FK_EB4C4D4E544BFD58 FOREIGN KEY (annee_universitaire_id) REFERENCES annee_universitaire (id)');
        $this->addSql('ALTER TABLE modification_note ADD CONSTRAINT FK_607975E526ED0855 FOREIGN KEY (note_id) REFERENCES note (id)');
        $this->addSql('ALTER TABLE modification_note ADD CONSTRAINT FK_607975E51C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE ufr ADD CONSTRAINT FK_20D7AF9853C59D72 FOREIGN KEY (responsable_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE ufr ADD CONSTRAINT FK_20D7AF988CC2ED5D FOREIGN KEY (site_principal_id) REFERENCES site (id)');
        $this->addSql('ALTER TABLE ufr_site ADD CONSTRAINT FK_DD5A1B6AA469CB09 FOREIGN KEY (ufr_id) REFERENCES ufr (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ufr_site ADD CONSTRAINT FK_DD5A1B6AF6BD1646 FOREIGN KEY (site_id) REFERENCES site (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A768826AFA6 FOREIGN KEY (type_document_id) REFERENCES type_document (id)');
        $this->addSql('ALTER TABLE document_semestre ADD CONSTRAINT FK_FEA97EE5C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE document_semestre ADD CONSTRAINT FK_FEA97EE55577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE type_groupe ADD CONSTRAINT FK_276EE7195577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE competence ADD CONSTRAINT FK_94D4687F26F859E2 FOREIGN KEY (diplome_id) REFERENCES diplome (id)');
        $this->addSql('ALTER TABLE competence ADD CONSTRAINT FK_94D4687F727ACA70 FOREIGN KEY (parent_id) REFERENCES competence (id)');
        $this->addSql('ALTER TABLE stage_etudiant ADD CONSTRAINT FK_7999E68EBFDEDA6B FOREIGN KEY (stage_periode_id) REFERENCES stage_periode (id)');
        $this->addSql('ALTER TABLE stage_etudiant ADD CONSTRAINT FK_7999E68EDDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE stage_etudiant ADD CONSTRAINT FK_7999E68E86EC68D8 FOREIGN KEY (tuteur_id) REFERENCES contact (id)');
        $this->addSql('ALTER TABLE stage_etudiant ADD CONSTRAINT FK_7999E68E19FA6F23 FOREIGN KEY (tuteur_universitaire_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE stage_etudiant ADD CONSTRAINT FK_7999E68EA4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE stage_etudiant ADD CONSTRAINT FK_7999E68E428641F9 FOREIGN KEY (adresse_stage_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE absence_justificatif ADD CONSTRAINT FK_79296AB6DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE scolarite_moyenne_ue ADD CONSTRAINT FK_B78918B5AA6B2AB6 FOREIGN KEY (scolarite_id) REFERENCES scolarite (id)');
        $this->addSql('ALTER TABLE scolarite_moyenne_ue ADD CONSTRAINT FK_B78918B562E883B1 FOREIGN KEY (ue_id) REFERENCES ue (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C91C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE absence ADD CONSTRAINT FK_765AE0C9DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE site ADD CONSTRAINT FK_694309E44DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE ue ADD CONSTRAINT FK_2E490A9B5577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE stage_mail_template ADD CONSTRAINT FK_B64E584BBFDEDA6B FOREIGN KEY (stage_periode_id) REFERENCES stage_periode (id)');
        $this->addSql('ALTER TABLE stage_mail_template ADD CONSTRAINT FK_B64E584BB08B63B FOREIGN KEY (twig_template_id) REFERENCES twig_template (id)');
        $this->addSql('ALTER TABLE message_destinataire ADD CONSTRAINT FK_3AA8CA74537A1329 FOREIGN KEY (message_id) REFERENCES message (id)');
        $this->addSql('ALTER TABLE message_destinataire ADD CONSTRAINT FK_3AA8CA741C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE message_destinataire ADD CONSTRAINT FK_3AA8CA74DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE alternance ADD CONSTRAINT FK_445F37B9A4AEAFEA FOREIGN KEY (entreprise_id) REFERENCES entreprise (id)');
        $this->addSql('ALTER TABLE alternance ADD CONSTRAINT FK_445F37B986EC68D8 FOREIGN KEY (tuteur_id) REFERENCES contact (id)');
        $this->addSql('ALTER TABLE alternance ADD CONSTRAINT FK_445F37B9DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE alternance ADD CONSTRAINT FK_445F37B919FA6F23 FOREIGN KEY (tuteur_universitaire_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE alternance ADD CONSTRAINT FK_445F37B9543EC5F0 FOREIGN KEY (annee_id) REFERENCES annee (id)');
        $this->addSql('ALTER TABLE groupe ADD CONSTRAINT FK_4B98C21CE83749C FOREIGN KEY (type_groupe_id) REFERENCES type_groupe (id)');
        $this->addSql('ALTER TABLE groupe ADD CONSTRAINT FK_4B98C21727ACA70 FOREIGN KEY (parent_id) REFERENCES groupe (id)');
        $this->addSql('ALTER TABLE actualite ADD CONSTRAINT FK_54928197CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE stage_periode_interruption ADD CONSTRAINT FK_597C69BDBFDEDA6B FOREIGN KEY (stage_periode_id) REFERENCES stage_periode (id)');
        $this->addSql('ALTER TABLE materiel ADD CONSTRAINT FK_18D2B0915D91DD3E FOREIGN KEY (type_materiel_id) REFERENCES type_materiel (id)');
        $this->addSql('ALTER TABLE scolarite_moyenne_matiere ADD CONSTRAINT FK_25D9FE28AA6B2AB6 FOREIGN KEY (scolarite_id) REFERENCES scolarite (id)');
        $this->addSql('ALTER TABLE scolarite_moyenne_matiere ADD CONSTRAINT FK_25D9FE28F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE type_materiel ADD CONSTRAINT FK_D52D976DCCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE ppn ADD CONSTRAINT FK_2E8584EB26F859E2 FOREIGN KEY (diplome_id) REFERENCES diplome (id)');
        $this->addSql('ALTER TABLE trello_tache ADD CONSTRAINT FK_2589CEE0CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE trello_tache_personnel ADD CONSTRAINT FK_7D360FA2EBED4F1 FOREIGN KEY (trello_tache_id) REFERENCES trello_tache (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trello_tache_personnel ADD CONSTRAINT FK_7D360FA21C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message_piece_jointe ADD CONSTRAINT FK_6F502432537A1329 FOREIGN KEY (message_id) REFERENCES message (id)');
        $this->addSql('ALTER TABLE entreprise ADD CONSTRAINT FK_D19FA604DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE entreprise ADD CONSTRAINT FK_D19FA6053C59D72 FOREIGN KEY (responsable_id) REFERENCES contact (id)');
        $this->addSql('ALTER TABLE borne_semestre ADD CONSTRAINT FK_D1378E3B7F023A56 FOREIGN KEY (borne_id) REFERENCES borne (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE borne_semestre ADD CONSTRAINT FK_D1378E3B5577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F10335F61 FOREIGN KEY (expediteur_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14456C5646 FOREIGN KEY (evaluation_id) REFERENCES evaluation (id)');
        $this->addSql('ALTER TABLE note ADD CONSTRAINT FK_CFBDFA14DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE favori ADD CONSTRAINT FK_EF85A2CC9D7BCD43 FOREIGN KEY (etudiant_demandeur_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE favori ADD CONSTRAINT FK_EF85A2CC4E463162 FOREIGN KEY (etudiant_demande_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE previsionnel ADD CONSTRAINT FK_AE25C261F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE previsionnel ADD CONSTRAINT FK_AE25C2611C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A57566A6ABE2 FOREIGN KEY (personnel_auteur_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575727ACA70 FOREIGN KEY (parent_id) REFERENCES evaluation (id)');
        $this->addSql('ALTER TABLE evaluation ADD CONSTRAINT FK_1323A575CE83749C FOREIGN KEY (type_groupe_id) REFERENCES type_groupe (id)');
        $this->addSql('ALTER TABLE evaluation_personnel ADD CONSTRAINT FK_74BC385A456C5646 FOREIGN KEY (evaluation_id) REFERENCES evaluation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE evaluation_personnel ADD CONSTRAINT FK_74BC385A1C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE personnel_departement ADD CONSTRAINT FK_39139ED31C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE personnel_departement ADD CONSTRAINT FK_39139ED3CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E66CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E661C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE article_semestre ADD CONSTRAINT FK_24807BD77294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_semestre ADD CONSTRAINT FK_24807BD75577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_etudiant ADD CONSTRAINT FK_2496D6887294869C FOREIGN KEY (article_id) REFERENCES article (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_etudiant ADD CONSTRAINT FK_2496D688DDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scolarite ADD CONSTRAINT FK_276250AB5577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE scolarite ADD CONSTRAINT FK_276250ABDDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE scolarite ADD CONSTRAINT FK_276250AB544BFD58 FOREIGN KEY (annee_universitaire_id) REFERENCES annee_universitaire (id)');
        $this->addSql('ALTER TABLE salle ADD CONSTRAINT FK_4E977E5CF6BD1646 FOREIGN KEY (site_id) REFERENCES site (id)');
        $this->addSql('ALTER TABLE cahier_texte ADD CONSTRAINT FK_B554C6181C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE cahier_texte ADD CONSTRAINT FK_B554C6185577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE cahier_texte ADD CONSTRAINT FK_B554C618F46CD258 FOREIGN KEY (matiere_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE cahier_texte_fichier ADD CONSTRAINT FK_A095F9C885D2D268 FOREIGN KEY (cahier_texte_id) REFERENCES cahier_texte (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE cahier_texte_fichier ADD CONSTRAINT FK_A095F9C8F915CFE FOREIGN KEY (fichier_id) REFERENCES fichier (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE hrs ADD CONSTRAINT FK_6D8078785577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE hrs ADD CONSTRAINT FK_6D80787826F859E2 FOREIGN KEY (diplome_id) REFERENCES diplome (id)');
        $this->addSql('ALTER TABLE hrs ADD CONSTRAINT FK_6D8078781C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE hrs ADD CONSTRAINT FK_6D807878152AE753 FOREIGN KEY (type_hrs_id) REFERENCES type_hrs (id)');
        $this->addSql('ALTER TABLE hrs ADD CONSTRAINT FK_6D807878CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE creneau_bloque ADD CONSTRAINT FK_441F29EE7D0729A9 FOREIGN KEY (creneau_id) REFERENCES creneau_cours (id)');
        $this->addSql('ALTER TABLE creneau_bloque ADD CONSTRAINT FK_441F29EE122EEC90 FOREIGN KEY (semaine_id) REFERENCES calendrier (id)');
        $this->addSql('ALTER TABLE parcour ADD CONSTRAINT FK_B7E529565577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE scolarite_promo ADD CONSTRAINT FK_DDCE376C5577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE scolarite_promo ADD CONSTRAINT FK_DDCE376C544BFD58 FOREIGN KEY (annee_universitaire_id) REFERENCES annee_universitaire (id)');
        $this->addSql('ALTER TABLE date ADD CONSTRAINT FK_AA9E377ACCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE date_semestre ADD CONSTRAINT FK_B25DE61AB897366B FOREIGN KEY (date_id) REFERENCES date (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE date_semestre ADD CONSTRAINT FK_B25DE61A5577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT FK_C1765B63A469CB09 FOREIGN KEY (ufr_id) REFERENCES ufr (id)');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT FK_C1765B632AC98151 FOREIGN KEY (respri_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE departement ADD CONSTRAINT FK_C1765B63EB0464C9 FOREIGN KEY (annee_universitaire_prepare_id) REFERENCES annee_universitaire (id)');
        $this->addSql('ALTER TABLE stage_periode ADD CONSTRAINT FK_193A6DBE5577AFDB FOREIGN KEY (semestre_id) REFERENCES semestre (id)');
        $this->addSql('ALTER TABLE stage_periode_personnel ADD CONSTRAINT FK_30781912BFDEDA6B FOREIGN KEY (stage_periode_id) REFERENCES stage_periode (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stage_periode_personnel ADD CONSTRAINT FK_307819121C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE creneau_cours ADD CONSTRAINT FK_E844BB21544BFD58 FOREIGN KEY (annee_universitaire_id) REFERENCES annee_universitaire (id)');
        $this->addSql('ALTER TABLE creneau_cours ADD CONSTRAINT FK_E844BB21CCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE calendrier ADD CONSTRAINT FK_B2753CB9544BFD58 FOREIGN KEY (annee_universitaire_id) REFERENCES annee_universitaire (id)');
        $this->addSql('ALTER TABLE personnel ADD CONSTRAINT FK_A6BCF3DE4DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id)');
        $this->addSql('ALTER TABLE matiere ADD CONSTRAINT FK_9014574A62E883B1 FOREIGN KEY (ue_id) REFERENCES ue (id)');
        $this->addSql('ALTER TABLE matiere ADD CONSTRAINT FK_9014574A1CBD0BF FOREIGN KEY (ppn_id) REFERENCES ppn (id)');
        $this->addSql('ALTER TABLE matiere ADD CONSTRAINT FK_9014574A6E38C0DB FOREIGN KEY (parcours_id) REFERENCES parcour (id)');
        $this->addSql('ALTER TABLE matiere ADD CONSTRAINT FK_9014574AB7749956 FOREIGN KEY (matiere_parent_id) REFERENCES matiere (id)');
        $this->addSql('ALTER TABLE scolarite_promo_ue ADD CONSTRAINT FK_5A27D5E1CB57B82A FOREIGN KEY (scolarite_promo_id) REFERENCES scolarite_promo (id)');
        $this->addSql('ALTER TABLE scolarite_promo_ue ADD CONSTRAINT FK_5A27D5E162E883B1 FOREIGN KEY (ue_id) REFERENCES ue (id)');
        $this->addSql('ALTER TABLE annee ADD CONSTRAINT FK_DE92C5CF26F859E2 FOREIGN KEY (diplome_id) REFERENCES diplome (id)');
        $this->addSql('ALTER TABLE materiel_pret ADD CONSTRAINT FK_F2CBA05FCCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
        $this->addSql('ALTER TABLE materiel_pret ADD CONSTRAINT FK_F2CBA05FDDEAB1A3 FOREIGN KEY (etudiant_id) REFERENCES etudiant (id)');
        $this->addSql('ALTER TABLE materiel_pret ADD CONSTRAINT FK_F2CBA05F1C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE type_document ADD CONSTRAINT FK_1596AD8ACCF9E01E FOREIGN KEY (departement_id) REFERENCES departement (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE stage_periode_offre_stage_periode DROP FOREIGN KEY FK_3EBC879A818A1210');
        $this->addSql('ALTER TABLE semestre DROP FOREIGN KEY FK_71688FBC4F6564F9');
        $this->addSql('ALTER TABLE semestre DROP FOREIGN KEY FK_71688FBC9C2BB0CC');
        $this->addSql('ALTER TABLE semestre DROP FOREIGN KEY FK_71688FBCCF416101');
        $this->addSql('ALTER TABLE etudiant DROP FOREIGN KEY FK_717E22E35577AFDB');
        $this->addSql('ALTER TABLE document_semestre DROP FOREIGN KEY FK_FEA97EE55577AFDB');
        $this->addSql('ALTER TABLE type_groupe DROP FOREIGN KEY FK_276EE7195577AFDB');
        $this->addSql('ALTER TABLE ue DROP FOREIGN KEY FK_2E490A9B5577AFDB');
        $this->addSql('ALTER TABLE borne_semestre DROP FOREIGN KEY FK_D1378E3B5577AFDB');
        $this->addSql('ALTER TABLE article_semestre DROP FOREIGN KEY FK_24807BD75577AFDB');
        $this->addSql('ALTER TABLE scolarite DROP FOREIGN KEY FK_276250AB5577AFDB');
        $this->addSql('ALTER TABLE cahier_texte DROP FOREIGN KEY FK_B554C6185577AFDB');
        $this->addSql('ALTER TABLE hrs DROP FOREIGN KEY FK_6D8078785577AFDB');
        $this->addSql('ALTER TABLE parcour DROP FOREIGN KEY FK_B7E529565577AFDB');
        $this->addSql('ALTER TABLE scolarite_promo DROP FOREIGN KEY FK_DDCE376C5577AFDB');
        $this->addSql('ALTER TABLE date_semestre DROP FOREIGN KEY FK_B25DE61A5577AFDB');
        $this->addSql('ALTER TABLE stage_periode DROP FOREIGN KEY FK_193A6DBE5577AFDB');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CADDEAB1A3');
        $this->addSql('ALTER TABLE rattrapage DROP FOREIGN KEY FK_BDE5586DDDEAB1A3');
        $this->addSql('ALTER TABLE etudiant_groupe DROP FOREIGN KEY FK_10C7EA42DDEAB1A3');
        $this->addSql('ALTER TABLE stage_etudiant DROP FOREIGN KEY FK_7999E68EDDEAB1A3');
        $this->addSql('ALTER TABLE absence_justificatif DROP FOREIGN KEY FK_79296AB6DDEAB1A3');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9DDEAB1A3');
        $this->addSql('ALTER TABLE message_destinataire DROP FOREIGN KEY FK_3AA8CA74DDEAB1A3');
        $this->addSql('ALTER TABLE alternance DROP FOREIGN KEY FK_445F37B9DDEAB1A3');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14DDEAB1A3');
        $this->addSql('ALTER TABLE favori DROP FOREIGN KEY FK_EF85A2CC9D7BCD43');
        $this->addSql('ALTER TABLE favori DROP FOREIGN KEY FK_EF85A2CC4E463162');
        $this->addSql('ALTER TABLE article_etudiant DROP FOREIGN KEY FK_2496D688DDEAB1A3');
        $this->addSql('ALTER TABLE scolarite DROP FOREIGN KEY FK_276250ABDDEAB1A3');
        $this->addSql('ALTER TABLE materiel_pret DROP FOREIGN KEY FK_F2CBA05FDDEAB1A3');
        $this->addSql('ALTER TABLE hrs DROP FOREIGN KEY FK_6D807878152AE753');
        $this->addSql('ALTER TABLE competence DROP FOREIGN KEY FK_94D4687F26F859E2');
        $this->addSql('ALTER TABLE ppn DROP FOREIGN KEY FK_2E8584EB26F859E2');
        $this->addSql('ALTER TABLE hrs DROP FOREIGN KEY FK_6D80787826F859E2');
        $this->addSql('ALTER TABLE annee DROP FOREIGN KEY FK_DE92C5CF26F859E2');
        $this->addSql('ALTER TABLE stage_etudiant DROP FOREIGN KEY FK_7999E68E86EC68D8');
        $this->addSql('ALTER TABLE alternance DROP FOREIGN KEY FK_445F37B986EC68D8');
        $this->addSql('ALTER TABLE entreprise DROP FOREIGN KEY FK_D19FA6053C59D72');
        $this->addSql('ALTER TABLE ufr_site DROP FOREIGN KEY FK_DD5A1B6AA469CB09');
        $this->addSql('ALTER TABLE departement DROP FOREIGN KEY FK_C1765B63A469CB09');
        $this->addSql('ALTER TABLE document_semestre DROP FOREIGN KEY FK_FEA97EE5C33F7837');
        $this->addSql('ALTER TABLE stage_mail_template DROP FOREIGN KEY FK_B64E584BB08B63B');
        $this->addSql('ALTER TABLE groupe DROP FOREIGN KEY FK_4B98C21CE83749C');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A575CE83749C');
        $this->addSql('ALTER TABLE competence DROP FOREIGN KEY FK_94D4687F727ACA70');
        $this->addSql('ALTER TABLE cahier_texte_fichier DROP FOREIGN KEY FK_A095F9C8F915CFE');
        $this->addSql('ALTER TABLE ufr DROP FOREIGN KEY FK_20D7AF988CC2ED5D');
        $this->addSql('ALTER TABLE ufr_site DROP FOREIGN KEY FK_DD5A1B6AF6BD1646');
        $this->addSql('ALTER TABLE salle DROP FOREIGN KEY FK_4E977E5CF6BD1646');
        $this->addSql('ALTER TABLE scolarite_moyenne_ue DROP FOREIGN KEY FK_B78918B562E883B1');
        $this->addSql('ALTER TABLE matiere DROP FOREIGN KEY FK_9014574A62E883B1');
        $this->addSql('ALTER TABLE scolarite_promo_ue DROP FOREIGN KEY FK_5A27D5E162E883B1');
        $this->addSql('ALTER TABLE etudiant_groupe DROP FOREIGN KEY FK_10C7EA427A45358C');
        $this->addSql('ALTER TABLE groupe DROP FOREIGN KEY FK_4B98C21727ACA70');
        $this->addSql('ALTER TABLE materiel DROP FOREIGN KEY FK_18D2B0915D91DD3E');
        $this->addSql('ALTER TABLE diplome DROP FOREIGN KEY FK_EB4C4D4E544BFD58');
        $this->addSql('ALTER TABLE scolarite DROP FOREIGN KEY FK_276250AB544BFD58');
        $this->addSql('ALTER TABLE scolarite_promo DROP FOREIGN KEY FK_DDCE376C544BFD58');
        $this->addSql('ALTER TABLE departement DROP FOREIGN KEY FK_C1765B63EB0464C9');
        $this->addSql('ALTER TABLE creneau_cours DROP FOREIGN KEY FK_E844BB21544BFD58');
        $this->addSql('ALTER TABLE calendrier DROP FOREIGN KEY FK_B2753CB9544BFD58');
        $this->addSql('ALTER TABLE matiere DROP FOREIGN KEY FK_9014574A1CBD0BF');
        $this->addSql('ALTER TABLE trello_tache_personnel DROP FOREIGN KEY FK_7D360FA2EBED4F1');
        $this->addSql('ALTER TABLE stage_etudiant DROP FOREIGN KEY FK_7999E68EA4AEAFEA');
        $this->addSql('ALTER TABLE alternance DROP FOREIGN KEY FK_445F37B9A4AEAFEA');
        $this->addSql('ALTER TABLE borne_semestre DROP FOREIGN KEY FK_D1378E3B7F023A56');
        $this->addSql('ALTER TABLE message_destinataire DROP FOREIGN KEY FK_3AA8CA74537A1329');
        $this->addSql('ALTER TABLE message_piece_jointe DROP FOREIGN KEY FK_6F502432537A1329');
        $this->addSql('ALTER TABLE diplome DROP FOREIGN KEY FK_EB4C4D4E3BFB8FC7');
        $this->addSql('ALTER TABLE modification_note DROP FOREIGN KEY FK_607975E526ED0855');
        $this->addSql('ALTER TABLE note DROP FOREIGN KEY FK_CFBDFA14456C5646');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A575727ACA70');
        $this->addSql('ALTER TABLE evaluation_personnel DROP FOREIGN KEY FK_74BC385A456C5646');
        $this->addSql('ALTER TABLE article_semestre DROP FOREIGN KEY FK_24807BD77294869C');
        $this->addSql('ALTER TABLE article_etudiant DROP FOREIGN KEY FK_2496D6887294869C');
        $this->addSql('ALTER TABLE scolarite_moyenne_ue DROP FOREIGN KEY FK_B78918B5AA6B2AB6');
        $this->addSql('ALTER TABLE scolarite_moyenne_matiere DROP FOREIGN KEY FK_25D9FE28AA6B2AB6');
        $this->addSql('ALTER TABLE salle_examen DROP FOREIGN KEY FK_65CF5313DC304035');
        $this->addSql('ALTER TABLE cahier_texte_fichier DROP FOREIGN KEY FK_A095F9C885D2D268');
        $this->addSql('ALTER TABLE matiere DROP FOREIGN KEY FK_9014574A6E38C0DB');
        $this->addSql('ALTER TABLE scolarite_promo_matiere DROP FOREIGN KEY FK_545B5C33CB57B82A');
        $this->addSql('ALTER TABLE scolarite_promo_ue DROP FOREIGN KEY FK_5A27D5E1CB57B82A');
        $this->addSql('ALTER TABLE date_semestre DROP FOREIGN KEY FK_B25DE61AB897366B');
        $this->addSql('ALTER TABLE etudiant DROP FOREIGN KEY FK_717E22E3E03F15C0');
        $this->addSql('ALTER TABLE salle_examen DROP FOREIGN KEY FK_65CF5313CCF9E01E');
        $this->addSql('ALTER TABLE diplome DROP FOREIGN KEY FK_EB4C4D4ECCF9E01E');
        $this->addSql('ALTER TABLE actualite DROP FOREIGN KEY FK_54928197CCF9E01E');
        $this->addSql('ALTER TABLE type_materiel DROP FOREIGN KEY FK_D52D976DCCF9E01E');
        $this->addSql('ALTER TABLE trello_tache DROP FOREIGN KEY FK_2589CEE0CCF9E01E');
        $this->addSql('ALTER TABLE personnel_departement DROP FOREIGN KEY FK_39139ED3CCF9E01E');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E66CCF9E01E');
        $this->addSql('ALTER TABLE hrs DROP FOREIGN KEY FK_6D807878CCF9E01E');
        $this->addSql('ALTER TABLE date DROP FOREIGN KEY FK_AA9E377ACCF9E01E');
        $this->addSql('ALTER TABLE creneau_cours DROP FOREIGN KEY FK_E844BB21CCF9E01E');
        $this->addSql('ALTER TABLE materiel_pret DROP FOREIGN KEY FK_F2CBA05FCCF9E01E');
        $this->addSql('ALTER TABLE type_document DROP FOREIGN KEY FK_1596AD8ACCF9E01E');
        $this->addSql('ALTER TABLE stage_periode_soutenance DROP FOREIGN KEY FK_DF1DB51FBFDEDA6B');
        $this->addSql('ALTER TABLE stage_periode_offre_stage_periode DROP FOREIGN KEY FK_3EBC879ABFDEDA6B');
        $this->addSql('ALTER TABLE stage_etudiant DROP FOREIGN KEY FK_7999E68EBFDEDA6B');
        $this->addSql('ALTER TABLE stage_mail_template DROP FOREIGN KEY FK_B64E584BBFDEDA6B');
        $this->addSql('ALTER TABLE stage_periode_interruption DROP FOREIGN KEY FK_597C69BDBFDEDA6B');
        $this->addSql('ALTER TABLE stage_periode_personnel DROP FOREIGN KEY FK_30781912BFDEDA6B');
        $this->addSql('ALTER TABLE indisponibilite_personnel DROP FOREIGN KEY FK_C98EDDB57D0729A9');
        $this->addSql('ALTER TABLE creneau_bloque DROP FOREIGN KEY FK_441F29EE7D0729A9');
        $this->addSql('ALTER TABLE etudiant DROP FOREIGN KEY FK_717E22E34DE7DC5C');
        $this->addSql('ALTER TABLE etudiant DROP FOREIGN KEY FK_717E22E3CD22752C');
        $this->addSql('ALTER TABLE stage_etudiant DROP FOREIGN KEY FK_7999E68E428641F9');
        $this->addSql('ALTER TABLE site DROP FOREIGN KEY FK_694309E44DE7DC5C');
        $this->addSql('ALTER TABLE entreprise DROP FOREIGN KEY FK_D19FA604DE7DC5C');
        $this->addSql('ALTER TABLE personnel DROP FOREIGN KEY FK_A6BCF3DE4DE7DC5C');
        $this->addSql('ALTER TABLE indisponibilite_personnel DROP FOREIGN KEY FK_C98EDDB5122EEC90');
        $this->addSql('ALTER TABLE creneau_bloque DROP FOREIGN KEY FK_441F29EE122EEC90');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CA1C109075');
        $this->addSql('ALTER TABLE rattrapage DROP FOREIGN KEY FK_BDE5586D1C109075');
        $this->addSql('ALTER TABLE semestre DROP FOREIGN KEY FK_71688FBCE2F2E760');
        $this->addSql('ALTER TABLE semestre DROP FOREIGN KEY FK_71688FBC9266B8BA');
        $this->addSql('ALTER TABLE semestre DROP FOREIGN KEY FK_71688FBCF782170E');
        $this->addSql('ALTER TABLE indisponibilite_personnel DROP FOREIGN KEY FK_C98EDDB51C109075');
        $this->addSql('ALTER TABLE diplome DROP FOREIGN KEY FK_EB4C4D4ED2D1AAE2');
        $this->addSql('ALTER TABLE diplome DROP FOREIGN KEY FK_EB4C4D4E39A24FD8');
        $this->addSql('ALTER TABLE modification_note DROP FOREIGN KEY FK_607975E51C109075');
        $this->addSql('ALTER TABLE ufr DROP FOREIGN KEY FK_20D7AF9853C59D72');
        $this->addSql('ALTER TABLE stage_etudiant DROP FOREIGN KEY FK_7999E68E19FA6F23');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C91C109075');
        $this->addSql('ALTER TABLE message_destinataire DROP FOREIGN KEY FK_3AA8CA741C109075');
        $this->addSql('ALTER TABLE alternance DROP FOREIGN KEY FK_445F37B919FA6F23');
        $this->addSql('ALTER TABLE trello_tache_personnel DROP FOREIGN KEY FK_7D360FA21C109075');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F10335F61');
        $this->addSql('ALTER TABLE previsionnel DROP FOREIGN KEY FK_AE25C2611C109075');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A57566A6ABE2');
        $this->addSql('ALTER TABLE evaluation_personnel DROP FOREIGN KEY FK_74BC385A1C109075');
        $this->addSql('ALTER TABLE personnel_departement DROP FOREIGN KEY FK_39139ED31C109075');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E661C109075');
        $this->addSql('ALTER TABLE cahier_texte DROP FOREIGN KEY FK_B554C6181C109075');
        $this->addSql('ALTER TABLE hrs DROP FOREIGN KEY FK_6D8078781C109075');
        $this->addSql('ALTER TABLE departement DROP FOREIGN KEY FK_C1765B632AC98151');
        $this->addSql('ALTER TABLE stage_periode_personnel DROP FOREIGN KEY FK_307819121C109075');
        $this->addSql('ALTER TABLE materiel_pret DROP FOREIGN KEY FK_F2CBA05F1C109075');
        $this->addSql('ALTER TABLE scolarite_promo_matiere DROP FOREIGN KEY FK_545B5C33F46CD258');
        $this->addSql('ALTER TABLE rattrapage DROP FOREIGN KEY FK_BDE5586DF46CD258');
        $this->addSql('ALTER TABLE absence DROP FOREIGN KEY FK_765AE0C9F46CD258');
        $this->addSql('ALTER TABLE scolarite_moyenne_matiere DROP FOREIGN KEY FK_25D9FE28F46CD258');
        $this->addSql('ALTER TABLE previsionnel DROP FOREIGN KEY FK_AE25C261F46CD258');
        $this->addSql('ALTER TABLE evaluation DROP FOREIGN KEY FK_1323A575F46CD258');
        $this->addSql('ALTER TABLE cahier_texte DROP FOREIGN KEY FK_B554C618F46CD258');
        $this->addSql('ALTER TABLE matiere DROP FOREIGN KEY FK_9014574AB7749956');
        $this->addSql('ALTER TABLE semestre DROP FOREIGN KEY FK_71688FBC543EC5F0');
        $this->addSql('ALTER TABLE alternance DROP FOREIGN KEY FK_445F37B9543EC5F0');
        $this->addSql('ALTER TABLE document DROP FOREIGN KEY FK_D8698A768826AFA6');
        $this->addSql('DROP TABLE stage_periode_soutenance');
        $this->addSql('DROP TABLE salle_examen');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE scolarite_promo_matiere');
        $this->addSql('DROP TABLE stage_periode_offre');
        $this->addSql('DROP TABLE stage_periode_offre_stage_periode');
        $this->addSql('DROP TABLE rattrapage');
        $this->addSql('DROP TABLE semestre');
        $this->addSql('DROP TABLE etudiant');
        $this->addSql('DROP TABLE etudiant_groupe');
        $this->addSql('DROP TABLE configuration');
        $this->addSql('DROP TABLE type_hrs');
        $this->addSql('DROP TABLE indisponibilite_personnel');
        $this->addSql('DROP TABLE diplome');
        $this->addSql('DROP TABLE modification_note');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE ufr');
        $this->addSql('DROP TABLE ufr_site');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE document_semestre');
        $this->addSql('DROP TABLE twig_template');
        $this->addSql('DROP TABLE type_groupe');
        $this->addSql('DROP TABLE competence');
        $this->addSql('DROP TABLE stage_etudiant');
        $this->addSql('DROP TABLE absence_justificatif');
        $this->addSql('DROP TABLE scolarite_moyenne_ue');
        $this->addSql('DROP TABLE fichier');
        $this->addSql('DROP TABLE absence');
        $this->addSql('DROP TABLE site');
        $this->addSql('DROP TABLE help');
        $this->addSql('DROP TABLE ue');
        $this->addSql('DROP TABLE stage_mail_template');
        $this->addSql('DROP TABLE message_destinataire');
        $this->addSql('DROP TABLE alternance');
        $this->addSql('DROP TABLE edt_planning');
        $this->addSql('DROP TABLE groupe');
        $this->addSql('DROP TABLE actualite');
        $this->addSql('DROP TABLE stage_periode_interruption');
        $this->addSql('DROP TABLE materiel');
        $this->addSql('DROP TABLE scolarite_moyenne_matiere');
        $this->addSql('DROP TABLE type_materiel');
        $this->addSql('DROP TABLE annee_universitaire');
        $this->addSql('DROP TABLE ppn');
        $this->addSql('DROP TABLE trello_tache');
        $this->addSql('DROP TABLE trello_tache_personnel');
        $this->addSql('DROP TABLE message_piece_jointe');
        $this->addSql('DROP TABLE entreprise');
        $this->addSql('DROP TABLE borne');
        $this->addSql('DROP TABLE borne_semestre');
        $this->addSql('DROP TABLE message');
        $this->addSql('DROP TABLE type_diplome');
        $this->addSql('DROP TABLE note');
        $this->addSql('DROP TABLE favori');
        $this->addSql('DROP TABLE previsionnel');
        $this->addSql('DROP TABLE evaluation');
        $this->addSql('DROP TABLE evaluation_personnel');
        $this->addSql('DROP TABLE personnel_departement');
        $this->addSql('DROP TABLE courrier');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE article_semestre');
        $this->addSql('DROP TABLE article_etudiant');
        $this->addSql('DROP TABLE scolarite');
        $this->addSql('DROP TABLE salle');
        $this->addSql('DROP TABLE cahier_texte');
        $this->addSql('DROP TABLE cahier_texte_fichier');
        $this->addSql('DROP TABLE hrs');
        $this->addSql('DROP TABLE creneau_bloque');
        $this->addSql('DROP TABLE parcour');
        $this->addSql('DROP TABLE scolarite_promo');
        $this->addSql('DROP TABLE date');
        $this->addSql('DROP TABLE date_semestre');
        $this->addSql('DROP TABLE bac');
        $this->addSql('DROP TABLE celcat_events');
        $this->addSql('DROP TABLE departement');
        $this->addSql('DROP TABLE stage_periode');
        $this->addSql('DROP TABLE stage_periode_personnel');
        $this->addSql('DROP TABLE creneau_cours');
        $this->addSql('DROP TABLE adresse');
        $this->addSql('DROP TABLE calendrier');
        $this->addSql('DROP TABLE personnel');
        $this->addSql('DROP TABLE matiere');
        $this->addSql('DROP TABLE scolarite_promo_ue');
        $this->addSql('DROP TABLE annee');
        $this->addSql('DROP TABLE materiel_pret');
        $this->addSql('DROP TABLE type_document');
    }
}
